# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ImmiMeet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImmiMeet
  pod "PubNub", "~> 4"
  # pod "ChatSDK", :path => “/Users/anama/Projects/Hackathon/iswitable9/chat-sdk-ios/ChatSDK"
  pod "ChatSDKCore", :path => "/Users/anama/Projects/Hackathon/iswitable9/chat-sdk-ios/ChatSDK/ChatSDKCore"
  pod "ChatSDKUI", :path => "/Users/anama/Projects/Hackathon/iswitable9/chat-sdk-ios/ChatSDK/ChatSDKUI"
  pod "ChatSDKCoreData", :path => "/Users/anama/Projects/Hackathon/iswitable9/chat-sdk-ios/ChatSDK/ChatSDKCoreData"
  pod "ChatSDKFirebaseAdapter", :path => "/Users/anama/Projects/Hackathon/iswitable9/chat-sdk-ios/ChatSDK/ChatSDKFirebaseAdapter"
  # pod "Firebase/Database"
  # pod "Firebase/Auth"
  # pod "Firebase/Core"

end
